name: Build docker images

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        id: mvn_build
        run: |
          mvn --batch-mode clean install -DskipTests

          cd ./shop-ui
          MAVEN_ARTEFACT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo 'Version of shop-ui artefact is '$MAVEN_ARTEFACT_VERSION
          echo ::set-output name=shop_ui_artefact_version::${MAVEN_ARTEFACT_VERSION}

          cd ../shop-admin-ui
          MAVEN_ARTEFACT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo 'Version of shop-admin-ui artefact is '$MAVEN_ARTEFACT_VERSION
          echo ::set-output name=shop_admin_ui_artefact_version::${MAVEN_ARTEFACT_VERSION}

      - name: Show builded files
        run: |
          ls -la ./shop-admin-ui/target
          ls -la ./shop-ui/target

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build shop-ui with Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: shop-ui
          tags: ghcr.io/${{ github.actor }}/shop-ui:latest
          build-args: |
            JAR_FILE=shop-ui-${{ steps.mvn_build.outputs.shop_ui_artefact_version }}.jar

      - name: Build shop-admin-ui with Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: shop-admin-ui
          tags: ghcr.io/${{ github.actor }}/shop-admin-ui:latest
          build-args: |
            JAR_FILE=shop-admin-ui-${{ steps.mvn_build.outputs.shop_admin_ui_artefact_version }}.jar
